### ISSUE TITLE
Breaking Change: Ta-Lib No longer works on MacOS Ventura (Intel)

### ISSUE THREAD

**Issue by WarrenN1** [TA-Lib/ta-lib-python#595]
TA-Lib Python no longer works on MacOS Ventura due to the SIPs implemented by Apple I believe.

```
warrenniles@Warrens-MacBook-Pro ~ % python3
Python 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 17:02:14) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import talib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/warrenniles/Library/Python/3.9/lib/python/site-packages/talib/__init__.py", line 93, in <module>
    from ._ta_lib import (
ImportError: dlopen(/Users/warrenniles/Library/Python/3.9/lib/python/site-packages/talib/_ta_lib.cpython-39-darwin.so, 0x0002): Library not loaded: /usr/lib/libta_lib.0.dylib
  Referenced from: <2CB7402C-D165-3D0D-8E51-3154A6178CA3> /Users/warrenniles/Library/Python/3.9/lib/python/site-packages/talib/_ta_lib.cpython-39-darwin.so
  Reason: tried: '/usr/lib/libta_lib.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/libta_lib.0.dylib' (no such file), '/usr/lib/libta_lib.0.dylib' (no such file, not in dyld cache)
```

This can be avoided when I run:
crsutil disable
in recover mode but this is very problematic.

Any tips on how to solve this?

**Comment by mrjbq7** [comment]
I don’t have that problem. Works great for me.

Any tips on how to reproduce?

**Comment by mrjbq7** [comment]
Closing old issue.
