### ISSUE TITLE
can not install pybinding keep giving my this error

### ISSUE THREAD

**Issue by mohamedyassincs** [TA-Lib/ta-lib-python#625]
CMake Error at CMakeLists.txt:2 (project):
        Generator

          NMake Makefiles

        does not support platform specification, but platform

          x64

        was specified.

      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      -- Building for: NMake Makefiles
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      CMake Error at CMakeLists.txt:2 (project):
        Generator

          NMake Makefiles

        does not support platform specification, but platform

          x64

        was specified.

      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\moham\AppData\Local\Temp\pip-req-build-bb4j_u4f\setup.py", line 73, in build_extension
          build()
        File "C:\Users\moham\AppData\Local\Temp\pip-req-build-bb4j_u4f\setup.py", line 69, in build
          check_call(["cmake", ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "C:\Users\moham\anaconda3\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\moham\\AppData\\Local\\Temp\\pip-req-build-bb4j_u4f', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\moham\\AppData\\Local\\Temp\\pip-req-build-bb4j_u4f\\build\\lib.win-amd64-cpython-311', '-DPYTHON_EXECUTABLE=C:\\Users\\moham\\anaconda3\\python.exe', '-DPB_WERROR=OFF', '-DPB_TESTS=OFF', '-DPB_NATIVE_SIMD=ON', '-DPB_MKL=OFF', '-DPB_CUDA=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\moham\\AppData\\Local\\Temp\\pip-req-build-bb4j_u4f\\build\\lib.win-amd64-cpython-311', '-A', 'x64']' returned non-zero exit status 1.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\moham\AppData\Local\Temp\pip-req-build-bb4j_u4f\setup.py", line 100, in <module>
          setup(
        File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\moham\anaconda3\Lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\moham\AppData\Local\Temp\pip-req-build-bb4j_u4f\setup.py", line 38, in run
          self.build_extension(ext)
        File "C:\Users\moham\AppData\Local\Temp\pip-req-build-bb4j_u4f\setup.py", line 76, in build_extension
          build()
        File "C:\Users\moham\AppData\Local\Temp\pip-req-build-bb4j_u4f\setup.py", line 69, in build
          check_call(["cmake", ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "C:\Users\moham\anaconda3\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\moham\\AppData\\Local\\Temp\\pip-req-build-bb4j_u4f', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\moham\\AppData\\Local\\Temp\\pip-req-build-bb4j_u4f\\build\\lib.win-amd64-cpython-311', '-DPYTHON_EXECUTABLE=C:\\Users\\moham\\anaconda3\\python.exe', '-DPB_WERROR=OFF', '-DPB_TESTS=OFF', '-DPB_NATIVE_SIMD=ON', '-DPB_MKL=OFF', '-DPB_CUDA=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\moham\\AppData\\Local\\Temp\\pip-req-build-bb4j_u4f\\build\\lib.win-amd64-cpython-311', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pybinding
  Running setup.py clean for pybinding
Failed to build pybinding
ERROR: Could not build wheels for pybinding, which is required to install pyproject.toml-based projects

**Comment by mrjbq7** [comment]
I could be missing something but I don’t see any mention of ta-lib in this error output. Thanks,On Nov 23, 2023, at 3:08 PM, mohamedyassincs ***@***.***> wrote:﻿
CMake Error at CMakeLists.txt:2 (project):
Generator
      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.


  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  -- Building for: NMake Makefiles
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Error at CMakeLists.txt:2 (project):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.


  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "C:\Users\moham\AppData\Local\Temp\pip-req-build-bb4j_u4f\setup.py", line 73, in build_extension
      build()
    File "C:\Users\moham\AppData\Local\Temp\pip-req-build-bb4j_u4f\setup.py", line 69, in build
      check_call(["cmake", ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "C:\Users\moham\anaconda3\Lib\subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\moham\\AppData\\Local\\Temp\\pip-req-build-bb4j_u4f', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\moham\\AppData\\Local\\Temp\\pip-req-build-bb4j_u4f\\build\\lib.win-amd64-cpython-311', '-DPYTHON_EXECUTABLE=C:\\Users\\moham\\anaconda3\\python.exe', '-DPB_WERROR=OFF', '-DPB_TESTS=OFF', '-DPB_NATIVE_SIMD=ON', '-DPB_MKL=OFF', '-DPB_CUDA=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\moham\\AppData\\Local\\Temp\\pip-req-build-bb4j_u4f\\build\\lib.win-amd64-cpython-311', '-A', 'x64']' returned non-zero exit status 1.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\moham\AppData\Local\Temp\pip-req-build-bb4j_u4f\setup.py", line 100, in <module>
      setup(
    File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
      super().run_command(command)
    File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\moham\anaconda3\Lib\site-packages\wheel\bdist_wheel.py", line 325, in run
      self.run_command("build")
    File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
      super().run_command(command)
    File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
      self.run_command(cmd_name)
    File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
      super().run_command(command)
    File "C:\Users\moham\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\moham\AppData\Local\Temp\pip-req-build-bb4j_u4f\setup.py", line 38, in run
      self.build_extension(ext)
    File "C:\Users\moham\AppData\Local\Temp\pip-req-build-bb4j_u4f\setup.py", line 76, in build_extension
      build()
    File "C:\Users\moham\AppData\Local\Temp\pip-req-build-bb4j_u4f\setup.py", line 69, in build
      check_call(["cmake", ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "C:\Users\moham\anaconda3\Lib\subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\moham\\AppData\\Local\\Temp\\pip-req-build-bb4j_u4f', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\moham\\AppData\\Local\\Temp\\pip-req-build-bb4j_u4f\\build\\lib.win-amd64-cpython-311', '-DPYTHON_EXECUTABLE=C:\\Users\\moham\\anaconda3\\python.exe', '-DPB_WERROR=OFF', '-DPB_TESTS=OFF', '-DPB_NATIVE_SIMD=ON', '-DPB_MKL=OFF', '-DPB_CUDA=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\moham\\AppData\\Local\\Temp\\pip-req-build-bb4j_u4f\\build\\lib.win-amd64-cpython-311', '-A', 'x64']' returned non-zero exit status 1.
  [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for pybinding
Running setup.py clean for pybinding
Failed to build pybinding
ERROR: Could not build wheels for pybinding, which is required to install pyproject.toml-based projects
